name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: PDF
          path: main.pdf
      - name: Upload file to repository
        run: |
          git config --global user.name "lalitkumarj"
          git config --global user.email "lalitkumarj@gmail.com"
          git add main.pdf
          git commit -m "commit message"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        
